# Slimcoin - Fully Static Local Build

PREFIX ?= $(HOME)/slimcoin-libs/prefix
USE_UPNP ?= 0

DEFS = \
  -DBOOST_THREAD_USE_LIB \
  -DBOOST_SPIRIT_THREADSAFE \
  -DBOOST_NO_CXX11_SCOPED_ENUMS \
  -DUSE_UPNP=$(USE_UPNP) \
  -DHAVE_BUILD_INFO \
  -I$(CURDIR) -I$(CURDIR)/obj \
  -I$(PREFIX)/include \
  -I$(PREFIX)/include/miniupnpc \
  -I$(PREFIX)/include/openssl

CXXFLAGS = -O2 -std=c++11 \
  -pthread \
  -Wall -Wextra -Wno-sign-compare -Wformat-security \
  -fstack-protector-all \
  -D_FORTIFY_SOURCE=2 \
  -g3

# Fully static linking
LDFLAGS = \
  -static \
  -L$(PREFIX)/lib

BOOST_LIBS = \
  -lboost_system -lboost_filesystem \
  -lboost_program_options -lboost_thread

CRYPTO_LIBS = -lssl -lcrypto
DB_LIBS = -ldb_cxx

BASE_LIBS = -lz -lpthread -ldl -lrt

ifeq ($(USE_UPNP),1)
  UPNP_LIBS = -lminiupnpc
else
  UPNP_LIBS =
  DEFS += -DUSE_UPNP=0
endif

LIBS = $(BOOST_LIBS) $(CRYPTO_LIBS) $(DB_LIBS) $(UPNP_LIBS) $(BASE_LIBS)

OBJS = \
  obj/version.o obj/checkpoints.o obj/netbase.o obj/addrman.o \
  obj/crypter.o obj/key.o obj/db.o obj/init.o obj/irc.o obj/keystore.o \
  obj/main.o obj/net.o obj/protocol.o obj/bitcoinrpc.o obj/rpcdump.o \
  obj/rpccrypto.o obj/script.o obj/util.o obj/wallet.o obj/walletdb.o \
  obj/noui.o obj/kernel.o obj/dcrypt.o obj/smalldata.o obj/sha256.o \
  obj/ecies.o obj/secure.o obj/kdf.o obj/script_error.o

all: slimcoind

obj/build.h: FORCE
	@/bin/sh ../share/genbuild.sh obj/build.h

version.cpp: obj/build.h

obj/%.o: %.cpp
	$(CXX) -c $(CXXFLAGS) $(DEFS) -MMD -o $@ $<
	@cp $(@:.o=.d) $(@:.o=.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' \
	      -e 's/ *\\$$//' -e '/^$$/ d' \
	      -e 's/$$/ :/' < $(@:.o=.d) >> $(@:.o=.P); \
	  rm -f $(@:.o=.d)

obj/ecies.o: ecies/ecies.c
	$(CC) -c $(DEFS) -I$(PREFIX)/include -o $@ $<

obj/secure.o: ecies/secure.c
	$(CC) -c $(DEFS) -I$(PREFIX)/include -o $@ $<

obj/kdf.o: ecies/kdf.c
	$(CC) -c $(DEFS) -I$(PREFIX)/include -o $@ $<

slimcoind: $(OBJS)
	$(CXX) $(LDFLAGS) -o $@ $^ $(LIBS)

clean:
	rm -f slimcoind obj/*.o obj/*.P obj/build.h

FORCE:
