# Slimcoin - Static userland build (Boost+OpenSSL static, glibc dynamic)

PREFIX = $(CURDIR)/../depends/work/stage-x86_64-linux-gnu
#PREFIX ?= $(HOME)/slimcoin-libs/prefix
USE_UPNP ?= 0

DEFS = \
  -DBOOST_THREAD_USE_LIB \
  -DBOOST_SPIRIT_THREADSAFE \
  -DBOOST_NO_CXX11_SCOPED_ENUMS \
  -DUSE_UPNP=$(USE_UPNP) \
  -DHAVE_BUILD_INFO \
  -I$(CURDIR) -I$(CURDIR)/obj \
  -I$(PREFIX)/include \
  -I$(PREFIX)/include/miniupnpc \
  -I$(PREFIX)/include/openssl

CXXFLAGS = -O2 -std=c++11 \
  -pthread \
  -Wall -Wextra -Wno-sign-compare -Wformat-security \
  -fstack-protector-all -D_FORTIFY_SOURCE=2 -g3

ifeq ($(USE_UPNP),1)
  DEFS += -DUSE_UPNP=1
else
  DEFS += -DUSE_UPNP=0
endif

OBJS = \
  obj/version.o obj/checkpoints.o obj/netbase.o obj/addrman.o \
  obj/crypter.o obj/key.o obj/db.o obj/init.o obj/irc.o obj/keystore.o \
  obj/main.o obj/net.o obj/protocol.o obj/bitcoinrpc.o obj/rpcdump.o \
  obj/rpccrypto.o obj/script.o obj/util.o obj/wallet.o obj/walletdb.o \
  obj/noui.o obj/kernel.o obj/dcrypt.o obj/smalldata.o obj/sha256.o \
  obj/ecies.o obj/secure.o obj/kdf.o obj/script_error.o

# Local static archives (force exact .a use)
OPENSSL_A   = $(PREFIX)/lib/libcrypto.a $(PREFIX)/lib/libssl.a
BDB_A       = $(PREFIX)/lib/libdb_cxx.a
BOOST_A     = $(PREFIX)/lib/libboost_system.a \
              $(PREFIX)/lib/libboost_filesystem.a \
              $(PREFIX)/lib/libboost_program_options.a \
              $(PREFIX)/lib/libboost_thread.a
UPNP_A      = $(PREFIX)/lib/libminiupnpc.a

all: obj/build.h slimcoind

obj/build.h: FORCE
	@/bin/sh ../share/genbuild.sh obj/build.h

version.cpp: obj/build.h

obj/%.o: %.cpp
	$(CXX) -c $(CXXFLAGS) $(DEFS) -MMD -o $@ $<
	@cp $(@:.o=.d) $(@:.o=.P); \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' \
	      -e 's/ *\\$$//' -e '/^$$/ d' \
	      -e 's/$$/ :/' < $(@:.o=.d) >> $(@:.o=.P); \
	  rm -f $(@:.o=.d)

obj/ecies.o: ecies/ecies.c
	$(CC) -c $(DEFS) -I$(PREFIX)/include -o $@ $<

obj/secure.o: ecies/secure.c
	$(CC) -c $(DEFS) -I$(PREFIX)/include -o $@ $<

obj/kdf.o: ecies/kdf.c
	$(CC) -c $(DEFS) -I$(PREFIX)/include -o $@ $<

#slimcoind: $(OBJS)
#	$(CXX) -static-libstdc++ -static-libgcc -L$(PREFIX)/lib \
#	  -Wl,--start-group \
#	    $(OPENSSL_A) \
#	    $(BDB_A) \
#	    $(BOOST_A) \
#	    $(if $(filter 1,$(USE_UPNP)),$(UPNP_A),) \
#	  -Wl,--end-group \
#	  -Wl,-Bdynamic -lpthread -ldl -lrt -lz \
#	  -o $@ $^


slimcoind: $(OBJS)
	$(CXX) -o $@ $^ \
	  -static-libstdc++ -static-libgcc -L$(PREFIX)/lib \
	  -Wl,--start-group \
	    $(PREFIX)/lib/libcrypto.a \
	    $(PREFIX)/lib/libssl.a \
	    $(PREFIX)/lib/libdb_cxx.a \
	    $(PREFIX)/lib/libboost_system.a \
	    $(PREFIX)/lib/libboost_filesystem.a \
	    $(PREFIX)/lib/libboost_program_options.a \
	    $(PREFIX)/lib/libboost_thread.a \
	    $(if $(filter 1,$(USE_UPNP)),$(PREFIX)/lib/libminiupnpc.a,) \
	  -Wl,--end-group \
	  -Wl,-Bdynamic \
	    -lpthread -ldl -lrt -lz

clean:
	rm -f slimcoind obj/*.o obj/*.P obj/build.h

FORCE:
